### ISSUE TITLE
error when using the script

### ISSUE THREAD

**Issue by ccavee** [lukearran/TvTimeToTrakt#60] opened 2024-07-06 05:44 UTC
I keep getting an error about which repeats 10 times then fails, how do i fix this?
![image](https://github.com/lukearran/TvTimeToTrakt/assets/174854102/753daa25-f861-495b-8729-b4f5b8cce7ae)

**Comment by AdClarky** [comment] 2024-07-06 08:25
Hey, it's no problem. 
Would you be able to send your README.md (with the client_id, client_secret and trakt_username censored)?
Could you also share your "tracking-prod-records.csv" and "tracking-prod-records-v2.csv" with me?

Also, I'd be careful in the future as the url in your screenshot contains information that you probably didn't want to share.

**Comment by AdClarky** [comment] 2024-07-06 09:28
I've just tried the script for Supergirl and it worked fine. Did you [install](https://github.com/lukearran/TvTimeToTrakt/blob/main/README.md#install-required-libraries) the required libraries?

**Comment by ccavee** [comment] 2024-07-06 15:36
Thanks for getting back, I'll try to provide as much without leaking anything. Also is there any way you message me on so I don't do that on accident? - user is just my github user if you don't mind that.

Now, im just a rookie so I might have messed something up, i didn't touch the README.md but here's the file:
[README.md](https://github.com/user-attachments/files/16116596/README.md)
Here's what my folder looks like:
![image](https://github.com/lukearran/TvTimeToTrakt/assets/174854102/0a013cc9-9226-40ad-80e4-840ec939f72b)
Here's the installed libraries, or I think atleast: 
![image](https://github.com/lukearran/TvTimeToTrakt/assets/174854102/76ad4f07-29ae-4795-8bfa-5d2f5c5ffeec)
Lastly, here's the files:
[tracking-prod-records.csv](https://github.com/user-attachments/files/16116604/tracking-prod-records.csv)
[tracking-prod-records-v2.csv](https://github.com/user-attachments/files/16116605/tracking-prod-records-v2.csv)
If there's anything else you need to see lmk and don't forget this is my first time trying something like this so I probably missed a step or two.

**Comment by AdClarky** [comment] 2024-07-06 15:59
Sorry I meant the config.json not the README, my bad.

**Comment by ccavee** [comment] 2024-07-06 16:05
lol here you go
![image](https://github.com/lukearran/TvTimeToTrakt/assets/174854102/3c48e57c-f62c-4aa8-8472-9ad97f0c619e)

**Comment by AdClarky** [comment] 2024-07-06 23:56
I've just tried to reproduce your error with no luck, even on a fresh install. The only conditions I think could be different are your client id, secret or username being incorrect, but even then it should be a different error.
Could you try again from scratch? Regenerate a new token, and follow the steps in the README again, and see if you get the same error, thank you.

**Comment by ccavee** [comment] 2024-07-07 06:09
Okay I figured something out, trying on my brothers computer works.
So for some reason I was facing the error https://github.com/lukearran/TvTimeToTrakt/issues/40
So I changed it as someone said to this: 
![image](https://github.com/lukearran/TvTimeToTrakt/assets/174854102/5118487e-d56f-469f-a150-56a9759f3681)
Which ended up giving me that error earlier. 

For some reason on my brothers computer the authorization link worked fine and was actually the correct place. 

I don't know if that helps you fix the issue or anything but that's what it was. Also I'm on win11 while my brother is on win10.

I think its a problem with pytrakt and that "core" file in the previous issue.

**Comment by AdClarky** [comment] 2024-07-07 07:29
Trakt recently changed their API url to https://api.trakt.tv which messed with pytrakt. 
I'm going to close this issue since you got it working and pytrakt isn't directly related to this repo.

**Closed as not planned** 2024-07-07 07:29 UTC

**Comment by AdClarky** [comment] 2024-07-07 18:22
@ccavee what made you change the base-url initially?

**Comment by ccavee** [comment] 2024-07-07 20:09
On my computer to authorize, the link I had to open in google was something like: https://api-v2launch.trakt.tv/ -------------------------- with the rest of the link in the dashes. That link just sends me to something like this:
![image](https://github.com/lukearran/TvTimeToTrakt/assets/174854102/3ffe8b09-2187-4cc0-887b-92b36fe3edc7)

On my brother's PC, it got it first try and I didn't have to change anything and I was able to get the code to continue.

Not sure if that's an error with pytrakt or this repo, lemme know if you figure it out I'm curious lol.

**Comment by AdClarky** [comment] 2024-07-07 20:20
It’s just interesting because according to pytrakt, the depreciated API link was replaced in [version 3.4.25](https://github.com/glensc/python-pytrakt/releases/tag/3.4.25) and you have 3.4.32 installed which has [the correct link](https://github.com/glensc/python-pytrakt/blob/3c4a5fe76a5c79422eb8b5e403227e6311f899a5/trakt/core.py#L31). I just wonder how that link got in there. Have you used pytrakt before?

**Comment by ccavee** [comment] 2024-07-07 20:25
Oh, what the heck that's odd, not sure why I could've gotten the old link, I never used it before no, I made a Trakt account like last week lol, and this was also my first time downloading python to begin with also lol

**Comment by ccavee** [comment] 2024-07-09 03:55
Hi @AdClarky anyway you could delete this issue, since its kind of useless and related to here, also for privacy reason. Ty

**Comment by AdClarky** [comment] 2024-07-09 06:57
It’s good to keep things public so if anyone ends up having the same issue they can see how to fix it.
